### PR TITLE
Package pkg renamed into internal.

### PR DESCRIPTION
**Pull request by piotrkowalczuk**
The code stored in `pkg` looks like something that should be restricted only for internal use. `internal` directory in `GOPATH` put restrictions on a code that it contains. It is possible to import code from `internal` package only in the same `GOPATH` branch. `pkg` package is dedicated for libraries that are also meant to be used by client/caller.

More about this concept can be found [here](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit).

### CODE REVIEW

**Comment by pires** [comment]
@piotrkowalczuk the PR description is not enough. Can you please elaborate?

**Comment by piotrkowalczuk** [comment]
@pires done

**Comment by pires** [comment]
Sorry @piotrkowalczuk I've been quite busy with some issues regarding the development of some of the features and haven't been able to look at this properly.

I agree with the argument but I'm not sure all the code moved in this PR should be moved or not, e.g. code related to the operator APIs, which may be imported by separate projects.

After the dust is settled, and the team is satisfied with the delivery, I'll look back into this.

**Comment by pires** [comment]
@piotrkowalczuk can you please rebase?

**Comment by piotrkowalczuk** [comment]
@pires I'm trying, but #6 blocks me.

**Comment by pires** [comment]
Want to give it a shot now @piotrkowalczuk? I'm trying not to import any code from Kubernetes codebase as I don't want to maintain any dependencies.

**Comment by piotrkowalczuk** [comment]
Continued #8.

**Pull request closed without merging**
